# Generated by Django 5.2.8 on 2025-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['-last_scraped'], 'verbose_name': 'Page Content', 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
